# This is just here so the system can start up.
# The real configuration will be specific to each app that consumes this library.
site:
  name: 'Development SixCRM'
  domain: 'sixcrm.com'
  include_stage: true
